// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: proto/merger/v1/controlplane.proto

package mergerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangePacketRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePacketRef) Reset() {
	*x = ChangePacketRef{}
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePacketRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePacketRef) ProtoMessage() {}

func (x *ChangePacketRef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePacketRef.ProtoReflect.Descriptor instead.
func (*ChangePacketRef) Descriptor() ([]byte, []int) {
	return file_proto_merger_v1_controlplane_proto_rawDescGZIP(), []int{0}
}

func (x *ChangePacketRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EvidenceExecution struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChangePacketId string                 `protobuf:"bytes,1,opt,name=change_packet_id,json=changePacketId,proto3" json:"change_packet_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Required       bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	Summary        string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	DetailsUrl     string                 `protobuf:"bytes,7,opt,name=details_url,json=detailsUrl,proto3" json:"details_url,omitempty"`
	UpdatedBy      string                 `protobuf:"bytes,8,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EvidenceExecution) Reset() {
	*x = EvidenceExecution{}
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceExecution) ProtoMessage() {}

func (x *EvidenceExecution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceExecution.ProtoReflect.Descriptor instead.
func (*EvidenceExecution) Descriptor() ([]byte, []int) {
	return file_proto_merger_v1_controlplane_proto_rawDescGZIP(), []int{1}
}

func (x *EvidenceExecution) GetChangePacketId() string {
	if x != nil {
		return x.ChangePacketId
	}
	return ""
}

func (x *EvidenceExecution) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EvidenceExecution) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EvidenceExecution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EvidenceExecution) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *EvidenceExecution) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *EvidenceExecution) GetDetailsUrl() string {
	if x != nil {
		return x.DetailsUrl
	}
	return ""
}

func (x *EvidenceExecution) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *EvidenceExecution) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetChangePacketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *ChangePacketRef       `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChangePacketRequest) Reset() {
	*x = GetChangePacketRequest{}
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChangePacketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChangePacketRequest) ProtoMessage() {}

func (x *GetChangePacketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChangePacketRequest.ProtoReflect.Descriptor instead.
func (*GetChangePacketRequest) Descriptor() ([]byte, []int) {
	return file_proto_merger_v1_controlplane_proto_rawDescGZIP(), []int{2}
}

func (x *GetChangePacketRequest) GetRef() *ChangePacketRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type GetChangePacketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MergeLane     string                 `protobuf:"bytes,2,opt,name=merge_lane,json=mergeLane,proto3" json:"merge_lane,omitempty"`
	RiskScore     int32                  `protobuf:"varint,3,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Evidence      []*EvidenceExecution   `protobuf:"bytes,4,rep,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChangePacketResponse) Reset() {
	*x = GetChangePacketResponse{}
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChangePacketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChangePacketResponse) ProtoMessage() {}

func (x *GetChangePacketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChangePacketResponse.ProtoReflect.Descriptor instead.
func (*GetChangePacketResponse) Descriptor() ([]byte, []int) {
	return file_proto_merger_v1_controlplane_proto_rawDescGZIP(), []int{3}
}

func (x *GetChangePacketResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetChangePacketResponse) GetMergeLane() string {
	if x != nil {
		return x.MergeLane
	}
	return ""
}

func (x *GetChangePacketResponse) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *GetChangePacketResponse) GetEvidence() []*EvidenceExecution {
	if x != nil {
		return x.Evidence
	}
	return nil
}

type ListChangePacketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChangePacketsRequest) Reset() {
	*x = ListChangePacketsRequest{}
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChangePacketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChangePacketsRequest) ProtoMessage() {}

func (x *ListChangePacketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChangePacketsRequest.ProtoReflect.Descriptor instead.
func (*ListChangePacketsRequest) Descriptor() ([]byte, []int) {
	return file_proto_merger_v1_controlplane_proto_rawDescGZIP(), []int{4}
}

func (x *ListChangePacketsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ChangePacketSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	PrNumber      int32                  `protobuf:"varint,3,opt,name=pr_number,json=prNumber,proto3" json:"pr_number,omitempty"`
	MergeLane     string                 `protobuf:"bytes,4,opt,name=merge_lane,json=mergeLane,proto3" json:"merge_lane,omitempty"`
	RiskScore     int32                  `protobuf:"varint,5,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePacketSummary) Reset() {
	*x = ChangePacketSummary{}
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePacketSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePacketSummary) ProtoMessage() {}

func (x *ChangePacketSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePacketSummary.ProtoReflect.Descriptor instead.
func (*ChangePacketSummary) Descriptor() ([]byte, []int) {
	return file_proto_merger_v1_controlplane_proto_rawDescGZIP(), []int{5}
}

func (x *ChangePacketSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangePacketSummary) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *ChangePacketSummary) GetPrNumber() int32 {
	if x != nil {
		return x.PrNumber
	}
	return 0
}

func (x *ChangePacketSummary) GetMergeLane() string {
	if x != nil {
		return x.MergeLane
	}
	return ""
}

func (x *ChangePacketSummary) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

type ListChangePacketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ChangePacketSummary `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChangePacketsResponse) Reset() {
	*x = ListChangePacketsResponse{}
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChangePacketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChangePacketsResponse) ProtoMessage() {}

func (x *ListChangePacketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChangePacketsResponse.ProtoReflect.Descriptor instead.
func (*ListChangePacketsResponse) Descriptor() ([]byte, []int) {
	return file_proto_merger_v1_controlplane_proto_rawDescGZIP(), []int{6}
}

func (x *ListChangePacketsResponse) GetItems() []*ChangePacketSummary {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdateEvidenceExecutionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChangePacketId string                 `protobuf:"bytes,1,opt,name=change_packet_id,json=changePacketId,proto3" json:"change_packet_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Required       bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	Summary        string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	DetailsUrl     string                 `protobuf:"bytes,7,opt,name=details_url,json=detailsUrl,proto3" json:"details_url,omitempty"`
	UpdatedBy      string                 `protobuf:"bytes,8,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateEvidenceExecutionRequest) Reset() {
	*x = UpdateEvidenceExecutionRequest{}
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEvidenceExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEvidenceExecutionRequest) ProtoMessage() {}

func (x *UpdateEvidenceExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEvidenceExecutionRequest.ProtoReflect.Descriptor instead.
func (*UpdateEvidenceExecutionRequest) Descriptor() ([]byte, []int) {
	return file_proto_merger_v1_controlplane_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateEvidenceExecutionRequest) GetChangePacketId() string {
	if x != nil {
		return x.ChangePacketId
	}
	return ""
}

func (x *UpdateEvidenceExecutionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateEvidenceExecutionRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateEvidenceExecutionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateEvidenceExecutionRequest) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *UpdateEvidenceExecutionRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *UpdateEvidenceExecutionRequest) GetDetailsUrl() string {
	if x != nil {
		return x.DetailsUrl
	}
	return ""
}

func (x *UpdateEvidenceExecutionRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type UpdateEvidenceExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Evidence      *EvidenceExecution     `protobuf:"bytes,1,opt,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEvidenceExecutionResponse) Reset() {
	*x = UpdateEvidenceExecutionResponse{}
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEvidenceExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEvidenceExecutionResponse) ProtoMessage() {}

func (x *UpdateEvidenceExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEvidenceExecutionResponse.ProtoReflect.Descriptor instead.
func (*UpdateEvidenceExecutionResponse) Descriptor() ([]byte, []int) {
	return file_proto_merger_v1_controlplane_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateEvidenceExecutionResponse) GetEvidence() *EvidenceExecution {
	if x != nil {
		return x.Evidence
	}
	return nil
}

type EvidenceAuditEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChangePacketId string                 `protobuf:"bytes,2,opt,name=change_packet_id,json=changePacketId,proto3" json:"change_packet_id,omitempty"`
	EvidenceName   string                 `protobuf:"bytes,3,opt,name=evidence_name,json=evidenceName,proto3" json:"evidence_name,omitempty"`
	FromStatus     string                 `protobuf:"bytes,4,opt,name=from_status,json=fromStatus,proto3" json:"from_status,omitempty"`
	ToStatus       string                 `protobuf:"bytes,5,opt,name=to_status,json=toStatus,proto3" json:"to_status,omitempty"`
	Actor          string                 `protobuf:"bytes,6,opt,name=actor,proto3" json:"actor,omitempty"`
	Summary        string                 `protobuf:"bytes,7,opt,name=summary,proto3" json:"summary,omitempty"`
	DetailsUrl     string                 `protobuf:"bytes,8,opt,name=details_url,json=detailsUrl,proto3" json:"details_url,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OccurredAt     string                 `protobuf:"bytes,10,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EvidenceAuditEntry) Reset() {
	*x = EvidenceAuditEntry{}
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceAuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceAuditEntry) ProtoMessage() {}

func (x *EvidenceAuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceAuditEntry.ProtoReflect.Descriptor instead.
func (*EvidenceAuditEntry) Descriptor() ([]byte, []int) {
	return file_proto_merger_v1_controlplane_proto_rawDescGZIP(), []int{9}
}

func (x *EvidenceAuditEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EvidenceAuditEntry) GetChangePacketId() string {
	if x != nil {
		return x.ChangePacketId
	}
	return ""
}

func (x *EvidenceAuditEntry) GetEvidenceName() string {
	if x != nil {
		return x.EvidenceName
	}
	return ""
}

func (x *EvidenceAuditEntry) GetFromStatus() string {
	if x != nil {
		return x.FromStatus
	}
	return ""
}

func (x *EvidenceAuditEntry) GetToStatus() string {
	if x != nil {
		return x.ToStatus
	}
	return ""
}

func (x *EvidenceAuditEntry) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *EvidenceAuditEntry) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *EvidenceAuditEntry) GetDetailsUrl() string {
	if x != nil {
		return x.DetailsUrl
	}
	return ""
}

func (x *EvidenceAuditEntry) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EvidenceAuditEntry) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

type ListEvidenceAuditEntriesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChangePacketId string                 `protobuf:"bytes,1,opt,name=change_packet_id,json=changePacketId,proto3" json:"change_packet_id,omitempty"`
	Limit          int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListEvidenceAuditEntriesRequest) Reset() {
	*x = ListEvidenceAuditEntriesRequest{}
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEvidenceAuditEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEvidenceAuditEntriesRequest) ProtoMessage() {}

func (x *ListEvidenceAuditEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEvidenceAuditEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListEvidenceAuditEntriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_merger_v1_controlplane_proto_rawDescGZIP(), []int{10}
}

func (x *ListEvidenceAuditEntriesRequest) GetChangePacketId() string {
	if x != nil {
		return x.ChangePacketId
	}
	return ""
}

func (x *ListEvidenceAuditEntriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListEvidenceAuditEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*EvidenceAuditEntry  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEvidenceAuditEntriesResponse) Reset() {
	*x = ListEvidenceAuditEntriesResponse{}
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEvidenceAuditEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEvidenceAuditEntriesResponse) ProtoMessage() {}

func (x *ListEvidenceAuditEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEvidenceAuditEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListEvidenceAuditEntriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_merger_v1_controlplane_proto_rawDescGZIP(), []int{11}
}

func (x *ListEvidenceAuditEntriesResponse) GetItems() []*EvidenceAuditEntry {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_merger_v1_controlplane_proto protoreflect.FileDescriptor

const file_proto_merger_v1_controlplane_proto_rawDesc = "" +
	"\n" +
	"\"proto/merger/v1/controlplane.proto\x12\tmerger.v1\"!\n" +
	"\x0fChangePacketRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x92\x02\n" +
	"\x11EvidenceExecution\x12(\n" +
	"\x10change_packet_id\x18\x01 \x01(\tR\x0echangePacketId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\x12\x1f\n" +
	"\vdetails_url\x18\a \x01(\tR\n" +
	"detailsUrl\x12\x1d\n" +
	"\n" +
	"updated_by\x18\b \x01(\tR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"F\n" +
	"\x16GetChangePacketRequest\x12,\n" +
	"\x03ref\x18\x01 \x01(\v2\x1a.merger.v1.ChangePacketRefR\x03ref\"\xa1\x01\n" +
	"\x17GetChangePacketResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"merge_lane\x18\x02 \x01(\tR\tmergeLane\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x03 \x01(\x05R\triskScore\x128\n" +
	"\bevidence\x18\x04 \x03(\v2\x1c.merger.v1.EvidenceExecutionR\bevidence\"0\n" +
	"\x18ListChangePacketsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"\x94\x01\n" +
	"\x13ChangePacketSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x1b\n" +
	"\tpr_number\x18\x03 \x01(\x05R\bprNumber\x12\x1d\n" +
	"\n" +
	"merge_lane\x18\x04 \x01(\tR\tmergeLane\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x05 \x01(\x05R\triskScore\"Q\n" +
	"\x19ListChangePacketsResponse\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.merger.v1.ChangePacketSummaryR\x05items\"\x80\x02\n" +
	"\x1eUpdateEvidenceExecutionRequest\x12(\n" +
	"\x10change_packet_id\x18\x01 \x01(\tR\x0echangePacketId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\x12\x1f\n" +
	"\vdetails_url\x18\a \x01(\tR\n" +
	"detailsUrl\x12\x1d\n" +
	"\n" +
	"updated_by\x18\b \x01(\tR\tupdatedBy\"[\n" +
	"\x1fUpdateEvidenceExecutionResponse\x128\n" +
	"\bevidence\x18\x01 \x01(\v2\x1c.merger.v1.EvidenceExecutionR\bevidence\"\xa9\x03\n" +
	"\x12EvidenceAuditEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x10change_packet_id\x18\x02 \x01(\tR\x0echangePacketId\x12#\n" +
	"\revidence_name\x18\x03 \x01(\tR\fevidenceName\x12\x1f\n" +
	"\vfrom_status\x18\x04 \x01(\tR\n" +
	"fromStatus\x12\x1b\n" +
	"\tto_status\x18\x05 \x01(\tR\btoStatus\x12\x14\n" +
	"\x05actor\x18\x06 \x01(\tR\x05actor\x12\x18\n" +
	"\asummary\x18\a \x01(\tR\asummary\x12\x1f\n" +
	"\vdetails_url\x18\b \x01(\tR\n" +
	"detailsUrl\x12G\n" +
	"\bmetadata\x18\t \x03(\v2+.merger.v1.EvidenceAuditEntry.MetadataEntryR\bmetadata\x12\x1f\n" +
	"\voccurred_at\x18\n" +
	" \x01(\tR\n" +
	"occurredAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"a\n" +
	"\x1fListEvidenceAuditEntriesRequest\x12(\n" +
	"\x10change_packet_id\x18\x01 \x01(\tR\x0echangePacketId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"W\n" +
	" ListEvidenceAuditEntriesResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.merger.v1.EvidenceAuditEntryR\x05items2\xb7\x03\n" +
	"\x14ChangeControlService\x12X\n" +
	"\x0fGetChangePacket\x12!.merger.v1.GetChangePacketRequest\x1a\".merger.v1.GetChangePacketResponse\x12^\n" +
	"\x11ListChangePackets\x12#.merger.v1.ListChangePacketsRequest\x1a$.merger.v1.ListChangePacketsResponse\x12p\n" +
	"\x17UpdateEvidenceExecution\x12).merger.v1.UpdateEvidenceExecutionRequest\x1a*.merger.v1.UpdateEvidenceExecutionResponse\x12s\n" +
	"\x18ListEvidenceAuditEntries\x12*.merger.v1.ListEvidenceAuditEntriesRequest\x1a+.merger.v1.ListEvidenceAuditEntriesResponseB7Z5github.com/devr-tools/merger/proto/merger/v1;mergerv1b\x06proto3"

var (
	file_proto_merger_v1_controlplane_proto_rawDescOnce sync.Once
	file_proto_merger_v1_controlplane_proto_rawDescData []byte
)

func file_proto_merger_v1_controlplane_proto_rawDescGZIP() []byte {
	file_proto_merger_v1_controlplane_proto_rawDescOnce.Do(func() {
		file_proto_merger_v1_controlplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_merger_v1_controlplane_proto_rawDesc), len(file_proto_merger_v1_controlplane_proto_rawDesc)))
	})
	return file_proto_merger_v1_controlplane_proto_rawDescData
}

var file_proto_merger_v1_controlplane_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_merger_v1_controlplane_proto_goTypes = []any{
	(*ChangePacketRef)(nil),                  // 0: merger.v1.ChangePacketRef
	(*EvidenceExecution)(nil),                // 1: merger.v1.EvidenceExecution
	(*GetChangePacketRequest)(nil),           // 2: merger.v1.GetChangePacketRequest
	(*GetChangePacketResponse)(nil),          // 3: merger.v1.GetChangePacketResponse
	(*ListChangePacketsRequest)(nil),         // 4: merger.v1.ListChangePacketsRequest
	(*ChangePacketSummary)(nil),              // 5: merger.v1.ChangePacketSummary
	(*ListChangePacketsResponse)(nil),        // 6: merger.v1.ListChangePacketsResponse
	(*UpdateEvidenceExecutionRequest)(nil),   // 7: merger.v1.UpdateEvidenceExecutionRequest
	(*UpdateEvidenceExecutionResponse)(nil),  // 8: merger.v1.UpdateEvidenceExecutionResponse
	(*EvidenceAuditEntry)(nil),               // 9: merger.v1.EvidenceAuditEntry
	(*ListEvidenceAuditEntriesRequest)(nil),  // 10: merger.v1.ListEvidenceAuditEntriesRequest
	(*ListEvidenceAuditEntriesResponse)(nil), // 11: merger.v1.ListEvidenceAuditEntriesResponse
	nil,                                      // 12: merger.v1.EvidenceAuditEntry.MetadataEntry
}
var file_proto_merger_v1_controlplane_proto_depIdxs = []int32{
	0,  // 0: merger.v1.GetChangePacketRequest.ref:type_name -> merger.v1.ChangePacketRef
	1,  // 1: merger.v1.GetChangePacketResponse.evidence:type_name -> merger.v1.EvidenceExecution
	5,  // 2: merger.v1.ListChangePacketsResponse.items:type_name -> merger.v1.ChangePacketSummary
	1,  // 3: merger.v1.UpdateEvidenceExecutionResponse.evidence:type_name -> merger.v1.EvidenceExecution
	12, // 4: merger.v1.EvidenceAuditEntry.metadata:type_name -> merger.v1.EvidenceAuditEntry.MetadataEntry
	9,  // 5: merger.v1.ListEvidenceAuditEntriesResponse.items:type_name -> merger.v1.EvidenceAuditEntry
	2,  // 6: merger.v1.ChangeControlService.GetChangePacket:input_type -> merger.v1.GetChangePacketRequest
	4,  // 7: merger.v1.ChangeControlService.ListChangePackets:input_type -> merger.v1.ListChangePacketsRequest
	7,  // 8: merger.v1.ChangeControlService.UpdateEvidenceExecution:input_type -> merger.v1.UpdateEvidenceExecutionRequest
	10, // 9: merger.v1.ChangeControlService.ListEvidenceAuditEntries:input_type -> merger.v1.ListEvidenceAuditEntriesRequest
	3,  // 10: merger.v1.ChangeControlService.GetChangePacket:output_type -> merger.v1.GetChangePacketResponse
	6,  // 11: merger.v1.ChangeControlService.ListChangePackets:output_type -> merger.v1.ListChangePacketsResponse
	8,  // 12: merger.v1.ChangeControlService.UpdateEvidenceExecution:output_type -> merger.v1.UpdateEvidenceExecutionResponse
	11, // 13: merger.v1.ChangeControlService.ListEvidenceAuditEntries:output_type -> merger.v1.ListEvidenceAuditEntriesResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_merger_v1_controlplane_proto_init() }
func file_proto_merger_v1_controlplane_proto_init() {
	if File_proto_merger_v1_controlplane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_merger_v1_controlplane_proto_rawDesc), len(file_proto_merger_v1_controlplane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_merger_v1_controlplane_proto_goTypes,
		DependencyIndexes: file_proto_merger_v1_controlplane_proto_depIdxs,
		MessageInfos:      file_proto_merger_v1_controlplane_proto_msgTypes,
	}.Build()
	File_proto_merger_v1_controlplane_proto = out.File
	file_proto_merger_v1_controlplane_proto_goTypes = nil
	file_proto_merger_v1_controlplane_proto_depIdxs = nil
}
