// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v7.34.1
// source: proto/merger/v1/controlplane.proto

package mergerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangePacketRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ChangePacketRef) Reset() {
	*x = ChangePacketRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_merger_v1_controlplane_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangePacketRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePacketRef) ProtoMessage() {}

func (x *ChangePacketRef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePacketRef.ProtoReflect.Descriptor instead.
func (*ChangePacketRef) Descriptor() ([]byte, []int) {
	return file_proto_merger_v1_controlplane_proto_rawDescGZIP(), []int{0}
}

func (x *ChangePacketRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EvidenceExecution struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChangePacketId string `protobuf:"bytes,1,opt,name=change_packet_id,json=changePacketId,proto3" json:"change_packet_id,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type           string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Status         string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Required       bool   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	Summary        string `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	DetailsUrl     string `protobuf:"bytes,7,opt,name=details_url,json=detailsUrl,proto3" json:"details_url,omitempty"`
	UpdatedBy      string `protobuf:"bytes,8,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	UpdatedAt      string `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *EvidenceExecution) Reset() {
	*x = EvidenceExecution{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_merger_v1_controlplane_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvidenceExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceExecution) ProtoMessage() {}

func (x *EvidenceExecution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceExecution.ProtoReflect.Descriptor instead.
func (*EvidenceExecution) Descriptor() ([]byte, []int) {
	return file_proto_merger_v1_controlplane_proto_rawDescGZIP(), []int{1}
}

func (x *EvidenceExecution) GetChangePacketId() string {
	if x != nil {
		return x.ChangePacketId
	}
	return ""
}

func (x *EvidenceExecution) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EvidenceExecution) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EvidenceExecution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EvidenceExecution) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *EvidenceExecution) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *EvidenceExecution) GetDetailsUrl() string {
	if x != nil {
		return x.DetailsUrl
	}
	return ""
}

func (x *EvidenceExecution) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *EvidenceExecution) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetChangePacketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ref *ChangePacketRef `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
}

func (x *GetChangePacketRequest) Reset() {
	*x = GetChangePacketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_merger_v1_controlplane_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChangePacketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChangePacketRequest) ProtoMessage() {}

func (x *GetChangePacketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChangePacketRequest.ProtoReflect.Descriptor instead.
func (*GetChangePacketRequest) Descriptor() ([]byte, []int) {
	return file_proto_merger_v1_controlplane_proto_rawDescGZIP(), []int{2}
}

func (x *GetChangePacketRequest) GetRef() *ChangePacketRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type GetChangePacketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MergeLane string               `protobuf:"bytes,2,opt,name=merge_lane,json=mergeLane,proto3" json:"merge_lane,omitempty"`
	RiskScore int32                `protobuf:"varint,3,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Evidence  []*EvidenceExecution `protobuf:"bytes,4,rep,name=evidence,proto3" json:"evidence,omitempty"`
}

func (x *GetChangePacketResponse) Reset() {
	*x = GetChangePacketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_merger_v1_controlplane_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChangePacketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChangePacketResponse) ProtoMessage() {}

func (x *GetChangePacketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChangePacketResponse.ProtoReflect.Descriptor instead.
func (*GetChangePacketResponse) Descriptor() ([]byte, []int) {
	return file_proto_merger_v1_controlplane_proto_rawDescGZIP(), []int{3}
}

func (x *GetChangePacketResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetChangePacketResponse) GetMergeLane() string {
	if x != nil {
		return x.MergeLane
	}
	return ""
}

func (x *GetChangePacketResponse) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *GetChangePacketResponse) GetEvidence() []*EvidenceExecution {
	if x != nil {
		return x.Evidence
	}
	return nil
}

type ListChangePacketsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListChangePacketsRequest) Reset() {
	*x = ListChangePacketsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_merger_v1_controlplane_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListChangePacketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChangePacketsRequest) ProtoMessage() {}

func (x *ListChangePacketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChangePacketsRequest.ProtoReflect.Descriptor instead.
func (*ListChangePacketsRequest) Descriptor() ([]byte, []int) {
	return file_proto_merger_v1_controlplane_proto_rawDescGZIP(), []int{4}
}

func (x *ListChangePacketsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ChangePacketSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Repo      string `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	PrNumber  int32  `protobuf:"varint,3,opt,name=pr_number,json=prNumber,proto3" json:"pr_number,omitempty"`
	MergeLane string `protobuf:"bytes,4,opt,name=merge_lane,json=mergeLane,proto3" json:"merge_lane,omitempty"`
	RiskScore int32  `protobuf:"varint,5,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
}

func (x *ChangePacketSummary) Reset() {
	*x = ChangePacketSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_merger_v1_controlplane_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangePacketSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePacketSummary) ProtoMessage() {}

func (x *ChangePacketSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePacketSummary.ProtoReflect.Descriptor instead.
func (*ChangePacketSummary) Descriptor() ([]byte, []int) {
	return file_proto_merger_v1_controlplane_proto_rawDescGZIP(), []int{5}
}

func (x *ChangePacketSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangePacketSummary) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *ChangePacketSummary) GetPrNumber() int32 {
	if x != nil {
		return x.PrNumber
	}
	return 0
}

func (x *ChangePacketSummary) GetMergeLane() string {
	if x != nil {
		return x.MergeLane
	}
	return ""
}

func (x *ChangePacketSummary) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

type ListChangePacketsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ChangePacketSummary `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ListChangePacketsResponse) Reset() {
	*x = ListChangePacketsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_merger_v1_controlplane_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListChangePacketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChangePacketsResponse) ProtoMessage() {}

func (x *ListChangePacketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChangePacketsResponse.ProtoReflect.Descriptor instead.
func (*ListChangePacketsResponse) Descriptor() ([]byte, []int) {
	return file_proto_merger_v1_controlplane_proto_rawDescGZIP(), []int{6}
}

func (x *ListChangePacketsResponse) GetItems() []*ChangePacketSummary {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdateEvidenceExecutionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChangePacketId string `protobuf:"bytes,1,opt,name=change_packet_id,json=changePacketId,proto3" json:"change_packet_id,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type           string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Status         string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Required       bool   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	Summary        string `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	DetailsUrl     string `protobuf:"bytes,7,opt,name=details_url,json=detailsUrl,proto3" json:"details_url,omitempty"`
	UpdatedBy      string `protobuf:"bytes,8,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
}

func (x *UpdateEvidenceExecutionRequest) Reset() {
	*x = UpdateEvidenceExecutionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_merger_v1_controlplane_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEvidenceExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEvidenceExecutionRequest) ProtoMessage() {}

func (x *UpdateEvidenceExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEvidenceExecutionRequest.ProtoReflect.Descriptor instead.
func (*UpdateEvidenceExecutionRequest) Descriptor() ([]byte, []int) {
	return file_proto_merger_v1_controlplane_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateEvidenceExecutionRequest) GetChangePacketId() string {
	if x != nil {
		return x.ChangePacketId
	}
	return ""
}

func (x *UpdateEvidenceExecutionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateEvidenceExecutionRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateEvidenceExecutionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateEvidenceExecutionRequest) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *UpdateEvidenceExecutionRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *UpdateEvidenceExecutionRequest) GetDetailsUrl() string {
	if x != nil {
		return x.DetailsUrl
	}
	return ""
}

func (x *UpdateEvidenceExecutionRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type UpdateEvidenceExecutionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Evidence *EvidenceExecution `protobuf:"bytes,1,opt,name=evidence,proto3" json:"evidence,omitempty"`
}

func (x *UpdateEvidenceExecutionResponse) Reset() {
	*x = UpdateEvidenceExecutionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_merger_v1_controlplane_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEvidenceExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEvidenceExecutionResponse) ProtoMessage() {}

func (x *UpdateEvidenceExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merger_v1_controlplane_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEvidenceExecutionResponse.ProtoReflect.Descriptor instead.
func (*UpdateEvidenceExecutionResponse) Descriptor() ([]byte, []int) {
	return file_proto_merger_v1_controlplane_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateEvidenceExecutionResponse) GetEvidence() *EvidenceExecution {
	if x != nil {
		return x.Evidence
	}
	return nil
}

var File_proto_merger_v1_controlplane_proto protoreflect.FileDescriptor

var file_proto_merger_v1_controlplane_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x72, 0x2f, 0x76,
	0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22,
	0x21, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52,
	0x65, 0x66, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x92, 0x02, 0x0a, 0x11, 0x45, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x45,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x10, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x55, 0x72, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x46, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2c, 0x0a, 0x03, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x66, 0x52, 0x03, 0x72, 0x65, 0x66, 0x22,
	0xa1, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d,
	0x65, 0x72, 0x67, 0x65, 0x5f, 0x6c, 0x61, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x4c, 0x61, 0x6e, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x69,
	0x73, 0x6b, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x72, 0x69, 0x73, 0x6b, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x38, 0x0a, 0x08, 0x65, 0x76, 0x69,
	0x64, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x65,
	0x72, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x65, 0x76, 0x69, 0x64, 0x65,
	0x6e, 0x63, 0x65, 0x22, 0x30, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x94, 0x01, 0x0a, 0x13, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x72, 0x65, 0x70, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x70,
	0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1d,
	0x0a, 0x0a, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x5f, 0x6c, 0x61, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x4c, 0x61, 0x6e, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x72, 0x69, 0x73, 0x6b, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x72, 0x69, 0x73, 0x6b, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x51, 0x0a, 0x19,
	0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x65, 0x72, 0x67, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22,
	0x80, 0x02, 0x0a, 0x1e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x76, 0x69, 0x64, 0x65, 0x6e,
	0x63, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x55, 0x72, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x62,
	0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x42, 0x79, 0x22, 0x5b, 0x0a, 0x1f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x76, 0x69, 0x64,
	0x65, 0x6e, 0x63, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x08, 0x65, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x65, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x32,
	0xc2, 0x02, 0x0a, 0x14, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x58, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x21, 0x2e, 0x6d, 0x65,
	0x72, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x5e, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x12, 0x23, 0x2e, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6d,
	0x65, 0x72, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x70, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x76, 0x69, 0x64,
	0x65, 0x6e, 0x63, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x2e,
	0x6d, 0x65, 0x72, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x45, 0x76, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x6d, 0x65, 0x72, 0x67, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x76, 0x69, 0x64, 0x65,
	0x6e, 0x63, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x72, 0x68, 0x71, 0x2f, 0x6d, 0x65, 0x72, 0x67,
	0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x72, 0x2f,
	0x76, 0x31, 0x3b, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x72, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_merger_v1_controlplane_proto_rawDescOnce sync.Once
	file_proto_merger_v1_controlplane_proto_rawDescData = file_proto_merger_v1_controlplane_proto_rawDesc
)

func file_proto_merger_v1_controlplane_proto_rawDescGZIP() []byte {
	file_proto_merger_v1_controlplane_proto_rawDescOnce.Do(func() {
		file_proto_merger_v1_controlplane_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_merger_v1_controlplane_proto_rawDescData)
	})
	return file_proto_merger_v1_controlplane_proto_rawDescData
}

var file_proto_merger_v1_controlplane_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_merger_v1_controlplane_proto_goTypes = []any{
	(*ChangePacketRef)(nil),                 // 0: merger.v1.ChangePacketRef
	(*EvidenceExecution)(nil),               // 1: merger.v1.EvidenceExecution
	(*GetChangePacketRequest)(nil),          // 2: merger.v1.GetChangePacketRequest
	(*GetChangePacketResponse)(nil),         // 3: merger.v1.GetChangePacketResponse
	(*ListChangePacketsRequest)(nil),        // 4: merger.v1.ListChangePacketsRequest
	(*ChangePacketSummary)(nil),             // 5: merger.v1.ChangePacketSummary
	(*ListChangePacketsResponse)(nil),       // 6: merger.v1.ListChangePacketsResponse
	(*UpdateEvidenceExecutionRequest)(nil),  // 7: merger.v1.UpdateEvidenceExecutionRequest
	(*UpdateEvidenceExecutionResponse)(nil), // 8: merger.v1.UpdateEvidenceExecutionResponse
}
var file_proto_merger_v1_controlplane_proto_depIdxs = []int32{
	0, // 0: merger.v1.GetChangePacketRequest.ref:type_name -> merger.v1.ChangePacketRef
	1, // 1: merger.v1.GetChangePacketResponse.evidence:type_name -> merger.v1.EvidenceExecution
	5, // 2: merger.v1.ListChangePacketsResponse.items:type_name -> merger.v1.ChangePacketSummary
	1, // 3: merger.v1.UpdateEvidenceExecutionResponse.evidence:type_name -> merger.v1.EvidenceExecution
	2, // 4: merger.v1.ChangeControlService.GetChangePacket:input_type -> merger.v1.GetChangePacketRequest
	4, // 5: merger.v1.ChangeControlService.ListChangePackets:input_type -> merger.v1.ListChangePacketsRequest
	7, // 6: merger.v1.ChangeControlService.UpdateEvidenceExecution:input_type -> merger.v1.UpdateEvidenceExecutionRequest
	3, // 7: merger.v1.ChangeControlService.GetChangePacket:output_type -> merger.v1.GetChangePacketResponse
	6, // 8: merger.v1.ChangeControlService.ListChangePackets:output_type -> merger.v1.ListChangePacketsResponse
	8, // 9: merger.v1.ChangeControlService.UpdateEvidenceExecution:output_type -> merger.v1.UpdateEvidenceExecutionResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_merger_v1_controlplane_proto_init() }
func file_proto_merger_v1_controlplane_proto_init() {
	if File_proto_merger_v1_controlplane_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_merger_v1_controlplane_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ChangePacketRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_merger_v1_controlplane_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*EvidenceExecution); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_merger_v1_controlplane_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetChangePacketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_merger_v1_controlplane_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetChangePacketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_merger_v1_controlplane_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ListChangePacketsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_merger_v1_controlplane_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ChangePacketSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_merger_v1_controlplane_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ListChangePacketsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_merger_v1_controlplane_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateEvidenceExecutionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_merger_v1_controlplane_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateEvidenceExecutionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_merger_v1_controlplane_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_merger_v1_controlplane_proto_goTypes,
		DependencyIndexes: file_proto_merger_v1_controlplane_proto_depIdxs,
		MessageInfos:      file_proto_merger_v1_controlplane_proto_msgTypes,
	}.Build()
	File_proto_merger_v1_controlplane_proto = out.File
	file_proto_merger_v1_controlplane_proto_rawDesc = nil
	file_proto_merger_v1_controlplane_proto_goTypes = nil
	file_proto_merger_v1_controlplane_proto_depIdxs = nil
}
