// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v7.35.1
// source: proto/merger/v1/controlplane.proto

package mergerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	ChangeControlService_GetChangePacket_FullMethodName          = "/merger.v1.ChangeControlService/GetChangePacket"
	ChangeControlService_ListChangePackets_FullMethodName        = "/merger.v1.ChangeControlService/ListChangePackets"
	ChangeControlService_UpdateEvidenceExecution_FullMethodName  = "/merger.v1.ChangeControlService/UpdateEvidenceExecution"
	ChangeControlService_ListEvidenceAuditEntries_FullMethodName = "/merger.v1.ChangeControlService/ListEvidenceAuditEntries"
)

// ChangeControlServiceClient is the client API for ChangeControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChangeControlServiceClient interface {
	GetChangePacket(ctx context.Context, in *GetChangePacketRequest, opts ...grpc.CallOption) (*GetChangePacketResponse, error)
	ListChangePackets(ctx context.Context, in *ListChangePacketsRequest, opts ...grpc.CallOption) (*ListChangePacketsResponse, error)
	UpdateEvidenceExecution(ctx context.Context, in *UpdateEvidenceExecutionRequest, opts ...grpc.CallOption) (*UpdateEvidenceExecutionResponse, error)
	ListEvidenceAuditEntries(ctx context.Context, in *ListEvidenceAuditEntriesRequest, opts ...grpc.CallOption) (*ListEvidenceAuditEntriesResponse, error)
}

type changeControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChangeControlServiceClient(cc grpc.ClientConnInterface) ChangeControlServiceClient {
	return &changeControlServiceClient{cc}
}

func (c *changeControlServiceClient) GetChangePacket(ctx context.Context, in *GetChangePacketRequest, opts ...grpc.CallOption) (*GetChangePacketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChangePacketResponse)
	err := c.cc.Invoke(ctx, ChangeControlService_GetChangePacket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeControlServiceClient) ListChangePackets(ctx context.Context, in *ListChangePacketsRequest, opts ...grpc.CallOption) (*ListChangePacketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChangePacketsResponse)
	err := c.cc.Invoke(ctx, ChangeControlService_ListChangePackets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeControlServiceClient) UpdateEvidenceExecution(ctx context.Context, in *UpdateEvidenceExecutionRequest, opts ...grpc.CallOption) (*UpdateEvidenceExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEvidenceExecutionResponse)
	err := c.cc.Invoke(ctx, ChangeControlService_UpdateEvidenceExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changeControlServiceClient) ListEvidenceAuditEntries(ctx context.Context, in *ListEvidenceAuditEntriesRequest, opts ...grpc.CallOption) (*ListEvidenceAuditEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEvidenceAuditEntriesResponse)
	err := c.cc.Invoke(ctx, ChangeControlService_ListEvidenceAuditEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChangeControlServiceServer is the server API for ChangeControlService service.
// All implementations must embed UnimplementedChangeControlServiceServer
// for forward compatibility
type ChangeControlServiceServer interface {
	GetChangePacket(context.Context, *GetChangePacketRequest) (*GetChangePacketResponse, error)
	ListChangePackets(context.Context, *ListChangePacketsRequest) (*ListChangePacketsResponse, error)
	UpdateEvidenceExecution(context.Context, *UpdateEvidenceExecutionRequest) (*UpdateEvidenceExecutionResponse, error)
	ListEvidenceAuditEntries(context.Context, *ListEvidenceAuditEntriesRequest) (*ListEvidenceAuditEntriesResponse, error)
	mustEmbedUnimplementedChangeControlServiceServer()
}

// UnimplementedChangeControlServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChangeControlServiceServer struct {
}

func (UnimplementedChangeControlServiceServer) GetChangePacket(context.Context, *GetChangePacketRequest) (*GetChangePacketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChangePacket not implemented")
}
func (UnimplementedChangeControlServiceServer) ListChangePackets(context.Context, *ListChangePacketsRequest) (*ListChangePacketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChangePackets not implemented")
}
func (UnimplementedChangeControlServiceServer) UpdateEvidenceExecution(context.Context, *UpdateEvidenceExecutionRequest) (*UpdateEvidenceExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEvidenceExecution not implemented")
}
func (UnimplementedChangeControlServiceServer) ListEvidenceAuditEntries(context.Context, *ListEvidenceAuditEntriesRequest) (*ListEvidenceAuditEntriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEvidenceAuditEntries not implemented")
}
func (UnimplementedChangeControlServiceServer) mustEmbedUnimplementedChangeControlServiceServer() {}

// UnsafeChangeControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChangeControlServiceServer will
// result in compilation errors.
type UnsafeChangeControlServiceServer interface {
	mustEmbedUnimplementedChangeControlServiceServer()
}

func RegisterChangeControlServiceServer(s grpc.ServiceRegistrar, srv ChangeControlServiceServer) {
	s.RegisterService(&ChangeControlService_ServiceDesc, srv)
}

func _ChangeControlService_GetChangePacket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChangePacketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeControlServiceServer).GetChangePacket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeControlService_GetChangePacket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeControlServiceServer).GetChangePacket(ctx, req.(*GetChangePacketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeControlService_ListChangePackets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChangePacketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeControlServiceServer).ListChangePackets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeControlService_ListChangePackets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeControlServiceServer).ListChangePackets(ctx, req.(*ListChangePacketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeControlService_UpdateEvidenceExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEvidenceExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeControlServiceServer).UpdateEvidenceExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeControlService_UpdateEvidenceExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeControlServiceServer).UpdateEvidenceExecution(ctx, req.(*UpdateEvidenceExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangeControlService_ListEvidenceAuditEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEvidenceAuditEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangeControlServiceServer).ListEvidenceAuditEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangeControlService_ListEvidenceAuditEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangeControlServiceServer).ListEvidenceAuditEntries(ctx, req.(*ListEvidenceAuditEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChangeControlService_ServiceDesc is the grpc.ServiceDesc for ChangeControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChangeControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "merger.v1.ChangeControlService",
	HandlerType: (*ChangeControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChangePacket",
			Handler:    _ChangeControlService_GetChangePacket_Handler,
		},
		{
			MethodName: "ListChangePackets",
			Handler:    _ChangeControlService_ListChangePackets_Handler,
		},
		{
			MethodName: "UpdateEvidenceExecution",
			Handler:    _ChangeControlService_UpdateEvidenceExecution_Handler,
		},
		{
			MethodName: "ListEvidenceAuditEntries",
			Handler:    _ChangeControlService_ListEvidenceAuditEntries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/merger/v1/controlplane.proto",
}
